### ISSUE TITLE
Found a website that still won't let me copy

### ISSUE THREAD

**Issue by pogue** [jswanner/DontF-WithPaste#106]
The site is https://easyinfoblog.com and I'm not sure what kind of sorcery they're using to prevent highlighting and copying, but it won't allow you to do that. I tried blocking Javascript, but it prevented the page from loading.

Here's the page I was reading: https://easyinfoblog.com/technology/rip-amazon-prime-video/#6_Ways_to_rip_Amazon_Prime_Video_2020

Here's a pastebin of the source of the site: https://pastebin.com/mqdAWm5G

I'm running Don't Fuck With Paste version 2.7 on Opera x64 Version:73.0.3856.257. If you need any details about any other extensions I'm using, let me know. I also tried this in the latest Chrome with the same DFWP version and it didn't work either.

Thanks!
pogue

**Comment by jswanner** [comment]
@pogue,

It seems they are not actually intercepting `copy` browser events, instead they are preventing the selection of text using:

```css
*:not(input):not(textarea)::selection {
    background-color: transparent !important;
    color: inherit !important;
}

*:not(input):not(textarea)::-moz-selection {
    background-color: transparent !important;
    color: inherit !important;
}
```

They might also be intercepting the keyboard shortcut key events associated with copying as well.

This extension circumvents the most straight-forward approaches a website author can take to prevent copy, cut, and paste functionality. This extension does not try to circumvent all means by which a website author can take to prevent that functionality, partly because there are so many ways in which a website author can try to prevent those actions but also because this extension could end up causing more harm to your browsing experience if it did try to circumvent all the possible ways. Additionally, this extension generally allows for some workarounds for copy, cut, and paste when active event if keyboard shortcuts don't work (such as through right click or Edit menu).

I know it's frustrating when a website interferes with normal browsing behavior, and this extension tries to make things a little better. I don't think it's appropriate for this extension to circumvent what that site is doing, I think you'd be better off using something like [User CSS](https://chrome.google.com/webstore/detail/user-css/okpjlejfhacmgjkmknjhadmkdbcldfcb?hl=en) to address this problem.
